server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  mail:
    host: smtp.your-email-provider.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      enable-auto-commit: ${KAFKA_CONSUMER_ENABLE_AUTO_COMMIT:false}
      auto-commit-interval-ms: ${KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL_MS:5000}
      session-timeout-ms: ${KAFKA_CONSUMER_SESSION_TIMEOUT_MS:45000}
      heartbeat-interval-ms: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:3000}
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:500}
      max-poll-interval-ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:latest}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SECURITY_SASL_MECHANISM:PLAIN}
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  kafka:
    notification-consumer-topic: ${KAFKA_TOPIC_NOTIFICATION_CONSUMER:notification-consumer-topic}
    process-message-threadpool-size: ${PROCESS_MESSAGE_THREADPOOL_SIZE:25}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:asset-rest-service}



kafka:
  transaction:
    servers: localhost:9092
    ssl_endpoint_algorithm: ""
    consumerGroup: TRANSACTION_CONSUMER_GROUP
    maxPollRecords: 1000
    maxPollIntervals: 30000
    sessionTimeout: 60000
    concurrency: 3
    idleEventInterval : 60000
    security_enabled: false
    security_protocol: SSL
  fraud:
    servers: localhost:9092
    ssl_endpoint_algorithm: ""
    consumerGroup: FRAUD_CONSUMER_GROUP
    maxPollRecords: 1000
    maxPollIntervals: 30000
    sessionTimeout: 60000
    concurrency: 3
    idleEventInterval: 60000
    security_enabled: false
    security_protocol: SSL
  fraud1:
    servers: localhost:9092
    ssl_endpoint_algorithm: ""
    consumerGroup: FRAUD1_CONSUMER_GROUP
    maxPollRecords: 1000
    maxPollIntervals: 30000
    sessionTimeout: 60000
    concurrency: 3
    idleEventInterval: 60000
    security_enabled: false
    security_protocol: SSL
